/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiEmployeeRouteImport } from './routes/api/employee'
import { Route as appSigninRouteImport } from './routes/(app)/signin'
import { Route as appHistoryRouteImport } from './routes/(app)/history'
import { Route as appEmployeeRouteImport } from './routes/(app)/employee'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeRoute = ApiEmployeeRouteImport.update({
  id: '/api/employee',
  path: '/api/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const appSigninRoute = appSigninRouteImport.update({
  id: '/(app)/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const appHistoryRoute = appHistoryRouteImport.update({
  id: '/(app)/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const appEmployeeRoute = appEmployeeRouteImport.update({
  id: '/(app)/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof appEmployeeRoute
  '/history': typeof appHistoryRoute
  '/signin': typeof appSigninRoute
  '/api/employee': typeof ApiEmployeeRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee': typeof appEmployeeRoute
  '/history': typeof appHistoryRoute
  '/signin': typeof appSigninRoute
  '/api/employee': typeof ApiEmployeeRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/employee': typeof appEmployeeRoute
  '/(app)/history': typeof appHistoryRoute
  '/(app)/signin': typeof appSigninRoute
  '/api/employee': typeof ApiEmployeeRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/api/users': typeof ApiUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee'
    | '/history'
    | '/signin'
    | '/api/employee'
    | '/api/uploadthing'
    | '/api/users'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employee'
    | '/history'
    | '/signin'
    | '/api/employee'
    | '/api/uploadthing'
    | '/api/users'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/(app)/employee'
    | '/(app)/history'
    | '/(app)/signin'
    | '/api/employee'
    | '/api/uploadthing'
    | '/api/users'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appEmployeeRoute: typeof appEmployeeRoute
  appHistoryRoute: typeof appHistoryRoute
  appSigninRoute: typeof appSigninRoute
  ApiEmployeeRoute: typeof ApiEmployeeRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee': {
      id: '/api/employee'
      path: '/api/employee'
      fullPath: '/api/employee'
      preLoaderRoute: typeof ApiEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/signin': {
      id: '/(app)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof appSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/history': {
      id: '/(app)/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof appHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/employee': {
      id: '/(app)/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof appEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appEmployeeRoute: appEmployeeRoute,
  appHistoryRoute: appHistoryRoute,
  appSigninRoute: appSigninRoute,
  ApiEmployeeRoute: ApiEmployeeRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
