/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiEmployeeRouteImport } from './routes/api/employee'
import { Route as appEmployeeRouteImport } from './routes/(app)/employee'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmployeeRoute = ApiEmployeeRouteImport.update({
  id: '/api/employee',
  path: '/api/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const appEmployeeRoute = appEmployeeRouteImport.update({
  id: '/(app)/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee': typeof appEmployeeRoute
  '/api/employee': typeof ApiEmployeeRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee': typeof appEmployeeRoute
  '/api/employee': typeof ApiEmployeeRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)/employee': typeof appEmployeeRoute
  '/api/employee': typeof ApiEmployeeRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/employee' | '/api/employee' | '/api/uploadthing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/employee' | '/api/employee' | '/api/uploadthing'
  id:
    | '__root__'
    | '/'
    | '/(app)/employee'
    | '/api/employee'
    | '/api/uploadthing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appEmployeeRoute: typeof appEmployeeRoute
  ApiEmployeeRoute: typeof ApiEmployeeRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/employee': {
      id: '/api/employee'
      path: '/api/employee'
      fullPath: '/api/employee'
      preLoaderRoute: typeof ApiEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/employee': {
      id: '/(app)/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof appEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appEmployeeRoute: appEmployeeRoute,
  ApiEmployeeRoute: ApiEmployeeRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
